services:
- type: web
  name: final-project-line-bot
  env: node
  repo: https://github.com/tentacle203/final-project-line-bot.git
  buildCommand: npm install
  startCommand: node .
  plan: free
  autoDeploy: false
  envVars:
  - key: CHANNEL_ACCESS_TOKEN
    sync: false
  - key: CHANNEL_SECRET
    sync: false